site: 
  title: BG3 Modding Guides
  url: https://tom-project-strahd.github.io/project-strahd-modding-guides/devlogs/index.html
  start_page: devlogs:ROOT:index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: devlogs

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll