site: 
  title: Tom's BG3 Modding Wiki
  url: https://tom-project-strahd.github.io/project-strahd-modding-guides/
  robots: disallow
  start_page: wiki:ROOT:index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: wiki

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll